### ISSUE TITLE
EACCESS error to .git/objects/pack/ directory

### ISSUE THREAD

**Issue by stramel** [postcss/postcss-plugin-boilerplate#37]
Had to change permissions on the pack directory to get the start command to work. I doubt that is intended functionality.

Tried on:

Windows 7, GitBash and PowerShell

Ubuntu 16.04, Terminal

**Comment by ai** [comment]
I even have no access to `.git`😉. I think it is a your environment issue.

**Comment by rhysburnie** [comment]
Same `Error: EACCES: permission denied` when i tries to open a .idx file

macOS

**Comment by jamsinclair** [comment]
I had the same error on MacOS. I realised this was because I was running the `start` script from within the boilerplate repo directory. I wonder if we can detect this and throw error from the script?

The resolution was to follow the instructions precisely 😅 :
1. Clone the repo
2. Ensure you are at the parent directory just above the repo
3. From the parent directory run `node ./postcss-plugin-boilerplate/start`

**Comment by ai** [comment]
@jamsinclair Yeap. We can compare `process.cwd()` with `__dirname`. Do you want to send PR?
